### ISSUE TITLE
current vignette has lots of warnings

### ISSUE THREAD

**Issue by vjcitn** [stianlagstad/chimeraviz#43] opened 2018-05-21 18:13 UTC
have a look at

https://bioconductor.org/packages/release/bioc/vignettes/chimeraviz/inst/doc/chimeraviz-vignette.html

there are lots of

## length of NULL cannot be changed

in the document.  Let me know if you need more information.

**Comment by stianlagstad** [comment] 2018-05-22 06:16
Thank you for bringing this to my attention, @vjcitn! I believe it's caused by https://github.com/tidyverse/readr/issues/750, which now seem to have been fixed. I will look at it shortly.

**Comment by stianlagstad** [comment] 2018-09-16 13:27
Moving from readr to using data.table in https://github.com/stianlagstad/chimeraviz/commit/bd3f6fd2f7bf40e9fddbfa25fc25bb9384136095

The https://travis-ci.org/stianlagstad/chimeraviz/builds/429227218 build should go green. Will close this PR then.

**Comment by stianlagstad** [comment] 2018-09-16 14:27
OK for devel. Will do the same changes for release.

**Closed as completed by stianlagstad** 2018-09-16 14:27 UTC
